

spring.application.name=smartcart
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/smartcart
spring.datasource.username=smartcart_user
spring.datasource.password=smartcart123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Redis-configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
